export const DATA = [
    {
        id: '1',
        name: 'Горький шоколад',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный горький шоколад.',
    },
    {
        id: '2',
        name: 'Темный шоколад',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный темный шоколад.',
    },
    {
        id: '3',
        name: 'Молочный шоколад',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный молочный шоколад.',
    },
    {
        id: '4',
        name: 'Шоколад с грецким орехом',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный шоколад грецким орехом.',
    },
    {
        id: '5',
        name: 'Молочный шоколад с мендалем',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный молочный шоколад с мендалем.',
    },
    {
        id: '6',
        name: 'Большой молочный шоколад',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный молочный шоколад. Большая плитка.',
    },
    {
        id: '7',
        name: 'Большой гоколад с грецким орехом',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный шоколад грецким орехом. Большая плитка.',
    },
    {
        id: '8',
        name: 'Большой молочный шоколад с мендалем',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный молочный шоколад с мендалем. Большая плитка.',
    },
    {
        id: '9',
        name: 'Большой вкусный горький шоколад',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный горький шоколад. Большая плитка.',
    },
    {
        id: '10',
        name: 'Большой вкусный шоколад с грецким орехом',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный шоколад грецким орехом. Большая плитка.',
    },
    {
        id: '11',
        name: 'Большой вкусный молочный шоколад',
        price: 100,
        weight: 120,
        image: '/images/choco.jpg',
        description: 'Вкусный молочный шоколад с мендалем. Большая плитка.',
    },
]